// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-FQao4ft8ZFyt8DwSTqOlH_GPlG5niQ',
    appId: '1:939302248362:web:158f428c5cba1b721cd5d3',
    messagingSenderId: '939302248362',
    projectId: 'treasurehunt-flutter-spanmart',
    authDomain: 'treasurehunt-flutter-spanmart.firebaseapp.com',
    storageBucket: 'treasurehunt-flutter-spanmart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwQ7PzInBuA2WMtk3w5fUi1Txyx2KelHA',
    appId: '1:939302248362:android:2b931990f1e0569a1cd5d3',
    messagingSenderId: '939302248362',
    projectId: 'treasurehunt-flutter-spanmart',
    storageBucket: 'treasurehunt-flutter-spanmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIH4bVduhYYY3m5fvrKcu6My75HhFfg5A',
    appId: '1:939302248362:ios:522da2337b592f9e1cd5d3',
    messagingSenderId: '939302248362',
    projectId: 'treasurehunt-flutter-spanmart',
    storageBucket: 'treasurehunt-flutter-spanmart.appspot.com',
    iosClientId: '939302248362-anoc5ljbu1cfe21pas5e3qklncthdk57.apps.googleusercontent.com',
    iosBundleId: 'com.example.thehunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIH4bVduhYYY3m5fvrKcu6My75HhFfg5A',
    appId: '1:939302248362:ios:522da2337b592f9e1cd5d3',
    messagingSenderId: '939302248362',
    projectId: 'treasurehunt-flutter-spanmart',
    storageBucket: 'treasurehunt-flutter-spanmart.appspot.com',
    iosClientId: '939302248362-anoc5ljbu1cfe21pas5e3qklncthdk57.apps.googleusercontent.com',
    iosBundleId: 'com.example.thehunt',
  );
}
